# Generated by Django 4.2.2 on 2023-08-14 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0015_rename_cover_img_lecture_thumbnail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=108)),
                ('session_id', models.CharField(max_length=108)),
                ('currency', models.CharField(choices=[('USD', 'United States Dollar'), ('INR', 'Indian Rupee'), ('EUR', 'EURO'), ('RUB', 'Russian Ruble'), ('JPY', 'Japanese Yen'), ('AUD', 'Australian Dollar'), ('CNY', 'Chinese Yuan'), ('GBP', 'British Pound Sterling')], default='INR', max_length=3)),
                ('payment_status', models.CharField(max_length=18)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_course', to='course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
