# Generated by Django 4.2.2 on 2023-08-16 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_rename_cover_img_lecture_thumbnail_and_more'),
        ('payments', '0004_alter_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_course', to='course.course'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='enrollment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_enrollment', to='course.enroll'),
        ),
    ]
