# Generated by Django 4.2.2 on 2023-08-16 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_rename_cover_img_lecture_thumbnail_and_more'),
        ('payments', '0005_payment_course_alter_payment_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_course', to='course.course'),
        ),
    ]
