# Generated by Django 4.2.2 on 2023-07-14 05:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollments',
            field=models.ManyToManyField(blank=True, related_name='enrolled_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
