# Generated by Django 4.2.2 on 2023-07-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_review_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
