# Generated by Django 4.2.2 on 2023-08-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='captions',
            field=models.CharField(blank=True, max_length=108),
        ),
        migrations.AddField(
            model_name='course',
            name='languages',
            field=models.CharField(blank=True, max_length=108),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='preview_video',
            field=models.URLField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
