# Generated by Django 4.2.2 on 2023-08-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_captions_course_languages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='outcome',
            new_name='outcomes',
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('MA', 'Mathematics'), ('PH', 'Physics'), ('EC', 'Economics'), ('FM', 'Finance & Marketing'), ('CS', 'Computer Science'), ('NC', 'Not Categorized')], default='NC', max_length=32),
        ),
    ]
