# Generated by Django 4.2.2 on 2023-08-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_rename_outcome_course_outcomes_alter_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
