# Generated by Django 4.2.2 on 2023-08-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_lecture_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='currency',
            field=models.CharField(choices=[], default='INR', max_length=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Course Price'),
        ),
    ]
