# Generated by Django 4.2.2 on 2023-08-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_course_currency_alter_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='currency',
            field=models.CharField(choices=[('USD', 'USA'), ('INR', 'India')], default='INR', max_length=3),
        ),
    ]
