# Generated by Django 4.2.2 on 2023-08-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_course_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover_img',
            field=models.URLField(max_length=256),
        ),
        migrations.AlterField(
            model_name='course',
            name='currency',
            field=models.CharField(choices=[('USD', 'United States Dollar'), ('INR', 'Indian Rupee'), ('EUR', 'EURO'), ('RUB', 'Russian Ruble'), ('JPY', 'Japanese Yen'), ('AUD', 'Australian Dollar'), ('CNY', 'Chinese Yuan'), ('GBP', 'British Pound Sterling')], default='INR', max_length=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='course',
            name='languages',
            field=models.CharField(max_length=108),
        ),
        migrations.AlterField(
            model_name='course',
            name='outcomes',
            field=models.TextField(verbose_name='Outcome of the Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True, verbose_name='Prerequisites for the course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Course Price'),
        ),
    ]
