# Generated by Django 4.2.2 on 2023-08-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_alter_course_cover_img_alter_course_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='cover_img',
            new_name='thumbnail',
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_url',
            field=models.URLField(verbose_name='Lecture Url'),
        ),
    ]
