# Generated by Django 4.2.2 on 2023-08-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_rename_cover_img_lecture_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='totalRatings',
            field=models.IntegerField(default=0),
        ),
    ]
