# Generated by Django 4.2.2 on 2024-06-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_rename_user_review_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='description',
            field=models.CharField(blank=True, max_length=256, verbose_name='Lecture Description'),
        ),
    ]
